version: '3.8'
services:
  db:
    image: postgres:latest
    container_name: chatemo_postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: chatemo
    ports:
      - '5432:5432'
    volumes:
      - chatemo_postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U myuser']
      interval: 30s
      timeout: 10s
      retries: 5
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 512M
      placement:
        constraints:
          - node.role == manager

volumes:
  chatemo_postgres_data:
