version: '3.8'
services:
  db:
    image: postgres:latest
    container_name: chatemo-postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: chatemo
    ports:
      - '5432:5432'
    volumes:
      - chatemo-postgres-data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U myuser']
      interval: 30s
      timeout: 5s
      retries: 3
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 512M
      placement:
        constraints:
          - node.role == manager

  redis:
    image: redis:latest
    container_name: chatemo-redis
    ports:
      - '6379:6379'
    volumes:
      - chatemo-redis-data:/data
    environment:
      - REDIS_PASSWORD=password
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 30s
      timeout: 5s
      retries: 3
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: '512M'

volumes:
  chatemo-postgres-data:
  chatemo-redis-data:
