apiVersion: apps/v1
kind: Deployment
metadata:
  name: chatemo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: chatemo
  template:
    metadata:
      labels:
        app: chatemo
    spec:
      restartPolicy: Always
      containers:
        - name: chatemo
          image: australia-southeast1-docker.pkg.dev/chatemo/francizhong/chatemo:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          resources:
            requests:
              memory: '512Mi'
              cpu: '500m'
            limits:
              memory: '1Gi'
              cpu: '1'
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: env-secret
                  key: DATABASE_URL
            - name: REDIS_HOST
              value: 'redis'
            - name: REDIS_PORT
              value: '6379'
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: env-secret
                  key: REDIS_PASSWORD
            - name: NEXTAUTH_URL
              valueFrom:
                configMapKeyRef:
                  name: env-config
                  key: NEXTAUTH_URL
            - name: NEXTAUTH_SECRET
              valueFrom:
                secretKeyRef:
                  name: env-secret
                  key: NEXTAUTH_SECRET
            - name: GOOGLE_CLIENT_ID
              valueFrom:
                configMapKeyRef:
                  name: env-config
                  key: GOOGLE_CLIENT_ID
            - name: GOOGLE_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: env-config
                  key: GOOGLE_CLIENT_SECRET
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                configMapKeyRef:
                  name: env-config
                  key: AWS_ACCESS_KEY_ID
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: env-secret
                  key: AWS_SECRET_ACCESS_KEY
            - name: AWS_REGION
              valueFrom:
                configMapKeyRef:
                  name: env-config
                  key: AWS_REGION
            - name: AWS_S3_BUCKET_NAME
              valueFrom:
                configMapKeyRef:
                  name: env-config
                  key: AWS_S3_BUCKET_NAME
